<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CheckOutServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/CheckOutServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/CheckOutServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://reg.gf/">
    <import location="OrderProcessModule/wsdl/CheckOutService.wsdl" namespace="http://reg.gf/"/>
    
    <plnk:partnerLinkType name="CheckOutLinkType">
        <plnk:role name="CheckOutRole" portType="ns:CheckOut"/>
    </plnk:partnerLinkType>
</definitions>
