<?xml version="1.0" encoding="UTF-8"?>
<definitions
name="ProcessOrder"
targetNamespace="http://j2ee.netbeans.org/wsdl/ProcessOrder/ProcessOrder"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="http://j2ee.netbeans.org/wsdl/ProcessOrder/ProcessOrder"
    xmlns:ns="http://xml.netbeans.org/schema/ProcessOrder"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/ProcessOrder/ProcessOrder">
            <xsd:import namespace="http://xml.netbeans.org/schema/ProcessOrder" schemaLocation="ProcessOrder.xsd"/>
        </xsd:schema>
    </types>
    <message name="ProcessOrderOperationRequest">
        <part name="ProcessOrderInput" element="ns:typeA"/>
    </message>
    <message name="ProcessOrderOperationResponse">
        <part name="ProcessOrderOutput" element="ns:typeA"/>
    </message>
    <portType name="ProcessOrderPortType">
        <operation name="ProcessOrderOperation">
            <input name="input1" message="tns:ProcessOrderOperationRequest"/>
            <output name="output1" message="tns:ProcessOrderOperationResponse"/>
        </operation>
    </portType>
    <binding name="ProcessOrderBinding" type="tns:ProcessOrderPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProcessOrderOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="ProcessOrderService">
        <port name="ProcessOrderPort" binding="tns:ProcessOrderBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/ProcessOrderService/ProcessOrderPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="ProcessOrder">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ProcessOrderPortTypeRole" portType="tns:ProcessOrderPortType"/>
    </plnk:partnerLinkType>
</definitions>
